name: rest_o
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: ^2.0.0
  cached_network_image: ^2.5.0
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.1
  flutter_local_notifications: ^5.0.0
  flutter_native_splash: ^0.2.9
  google_fonts: ^1.1.2
  http: ^0.12.0+2
  intl: ^0.17.0
  lottie: ^0.7.0+1
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  smooth_star_rating: ^1.1.1
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.11.0
  mockito: ^4.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
