name: rest_o
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.0
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.1
  flutter_native_splash: ^0.2.9
  google_fonts: ^1.1.2
  http: ^0.12.0+2
  lottie: ^0.7.0+1
  provider: ^5.0.0
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
